[brainflow]
git-tree-sha1 = "d2476867e1e8261b9faacd7dbbb56cf8c3487219"
lazy = true

    [[brainflow.download]]
    sha256 = "869c886854f2e69a500c8f56ff0a6d7ada03abaa54e6eca6f92d036789dbda85"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.1.0/compiled_libs.tar"
